# Generated by Django 6.0 on 2025-12-22 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ('company__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ErpModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo ERP',
                'verbose_name_plural': 'Módulos ERP',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MatrixPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_authorize', models.BooleanField(default=False)),
                ('can_close', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('can_update_validity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso (matriz)',
                'verbose_name_plural': 'Permisos (matriz)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PermissionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('SCOPED', 'Scoped'), ('GLOBAL', 'Global')], max_length=12)),
                ('scoped_entity', models.CharField(blank=True, choices=[('COMPANY', 'Empresa'), ('BRANCH', 'Sucursal'), ('WAREHOUSE', 'Depósito'), ('CASH_REGISTER', 'Caja'), ('CONTROL_PANEL', 'Panel de control'), ('SELLER', 'Vendedor')], max_length=24, null=True)),
                ('global_entity', models.CharField(blank=True, choices=[('ACTION', 'Acciones'), ('MATRIX', 'Matriz'), ('PAYMENT_METHOD', 'Medios de pago')], max_length=24, null=True)),
                ('action_group', models.CharField(blank=True, help_text='Solo aplica para GLOBAL/ACTION. Exact match sobre ActionPermission.group.', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloque de permisos',
                'verbose_name_plural': 'Bloques de permisos',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PermissionVisibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('match_mode', models.CharField(choices=[('ANY', 'Cualquiera (ANY)')], default='ANY', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regla de visibilidad',
                'verbose_name_plural': 'Reglas de visibilidad',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ALTA', 'Alta'), ('MOD', 'Modificación'), ('BAJA', 'Baja')], default='ALTA', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('same_modules_for_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('department', models.CharField(blank=True, default='', max_length=160)),
                ('role_name', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de acceso',
                'verbose_name_plural': 'Templates de acceso',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=220)),
                ('value_type', models.CharField(choices=[('BOOL', 'Bool'), ('INT', 'Entero'), ('DECIMAL', 'Decimal'), ('PERCENT', 'Porcentaje'), ('TEXT', 'Texto')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('group', 'action'),
                'constraints': [models.UniqueConstraint(fields=('group', 'action'), name='uniq_actionperm_group_action')],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='catalog.branch')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ('branch__company__name', 'branch__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='catalog.company'),
        ),
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_panels', to='catalog.company')),
            ],
            options={
                'verbose_name': 'Panel de control',
                'verbose_name_plural': 'Paneles de control',
                'ordering': ('company__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ErpModuleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalog.erpmodule')),
            ],
            options={
                'verbose_name': 'Nivel ERP',
                'verbose_name_plural': 'Niveles ERP',
                'ordering': ('module__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ErpModuleSubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='catalog.erpmodulelevel')),
            ],
            options={
                'verbose_name': 'Subnivel ERP',
                'verbose_name_plural': 'Subniveles ERP',
                'ordering': ('level__module__name', 'level__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PermissionSelectionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_sets', to='catalog.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_sets', to='catalog.company')),
            ],
            options={
                'verbose_name': 'Selección de permisos',
                'verbose_name_plural': 'Selecciones de permisos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.accesstemplate')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Ítem de template',
                'verbose_name_plural': 'Ítems de template',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='accesstemplate',
            name='selection_set',
            field=models.ForeignKey(blank=True, help_text='LEGACY: se migrará a items. Evitar usarlo en lógica nueva.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates_legacy', to='catalog.permissionselectionset'),
        ),
        migrations.CreateModel(
            name='AccessRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.accessrequest')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud',
                'verbose_name_plural': 'Ítems de solicitud',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='selection_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.permissionselectionset'),
        ),
        migrations.CreateModel(
            name='PermissionVisibilityRuleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SHOW', 'Mostrar')], default='SHOW', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_rules', to='catalog.permissionblock')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_blocks', to='catalog.permissionvisibilityrule')),
            ],
            options={
                'verbose_name': 'Bloque por regla',
                'verbose_name_plural': 'Bloques por regla',
                'ordering': ('order', 'block__order', 'block__name'),
            },
        ),
        migrations.CreateModel(
            name='PermissionVisibilityTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.erpmodulelevel')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.erpmodule')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='catalog.permissionvisibilityrule')),
                ('sublevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.erpmodulesublevel')),
            ],
            options={
                'verbose_name': 'Trigger de visibilidad',
                'verbose_name_plural': 'Triggers de visibilidad',
            },
        ),
        migrations.CreateModel(
            name='RequestPersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=32, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_phone', models.CharField(max_length=40, verbose_name='Celular')),
                ('job_title', models.CharField(max_length=120, verbose_name='Puesto de trabajo')),
                ('direct_manager', models.CharField(max_length=120, verbose_name='Jefe directo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Datos de persona (solicitud)',
                'verbose_name_plural': 'Datos de personas (solicitudes)',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['dni'], name='catalog_req_dni_0b6b26_idx'), models.Index(fields=['last_name', 'first_name'], name='catalog_req_last_na_0c9649_idx'), models.Index(fields=['email'], name='catalog_req_email_aba5e8_idx')],
            },
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='person_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.requestpersondata'),
        ),
        migrations.CreateModel(
            name='SelectionSetActionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.actionpermission')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_values', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Acción (valor)',
                'verbose_name_plural': 'Acciones (valores)',
                'ordering': ('action_permission__group', 'action_permission__action'),
            },
        ),
        migrations.CreateModel(
            name='SelectionSetCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.cashregister')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Caja seleccionada',
                'verbose_name_plural': 'Cajas seleccionadas',
            },
        ),
        migrations.CreateModel(
            name='SelectionSetControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.controlpanel')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_panels', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Panel seleccionado',
                'verbose_name_plural': 'Paneles seleccionados',
            },
        ),
        migrations.CreateModel(
            name='SelectionSetLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.erpmodulelevel')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_levels', to='catalog.permissionselectionset')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionSetMatrixPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_authorize', models.BooleanField(default=False)),
                ('can_close', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('can_update_validity', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.matrixpermission')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_permissions', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Permiso de matriz (selección)',
                'verbose_name_plural': 'Permisos de matriz (selección)',
                'ordering': ('permission__name',),
            },
        ),
        migrations.CreateModel(
            name='SelectionSetModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.erpmodule')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_modules', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Módulo seleccionado',
                'verbose_name_plural': 'Módulos seleccionados',
            },
        ),
        migrations.AddField(
            model_name='permissionselectionset',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='selection_sets', through='catalog.SelectionSetModule', to='catalog.erpmodule'),
        ),
        migrations.CreateModel(
            name='SelectionSetPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.paymentmethodpermission')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Medio de pago (selección)',
                'verbose_name_plural': 'Medios de pago (selección)',
                'ordering': ('payment_method__name',),
            },
        ),
        migrations.CreateModel(
            name='SelectionSetSubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='catalog.permissionselectionset')),
                ('sublevel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.erpmodulesublevel')),
            ],
            options={
                'verbose_name': 'Subnivel seleccionado',
                'verbose_name_plural': 'Subniveles seleccionados',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='catalog.company')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ('company__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SelectionSetSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='catalog.permissionselectionset')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.seller')),
            ],
            options={
                'verbose_name': 'Vendedor seleccionado',
                'verbose_name_plural': 'Vendedores seleccionados',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='catalog.branch')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ('branch__company__name', 'branch__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SelectionSetWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='catalog.permissionselectionset')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse')),
            ],
            options={
                'verbose_name': 'Depósito seleccionado',
                'verbose_name_plural': 'Depósitos seleccionados',
            },
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_cashregister_per_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_branch_per_company_name'),
        ),
        migrations.AddConstraint(
            model_name='controlpanel',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_panel_per_company_name'),
        ),
        migrations.AddConstraint(
            model_name='erpmodulelevel',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='uniq_level_per_module_name'),
        ),
        migrations.AddConstraint(
            model_name='erpmodulesublevel',
            constraint=models.UniqueConstraint(fields=('level', 'name'), name='uniq_sublevel_per_level_name'),
        ),
        migrations.AddConstraint(
            model_name='accesstemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'selection_set'), name='uniq_template_selection_set'),
        ),
        migrations.AddConstraint(
            model_name='accesstemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_access_template_name'),
        ),
        migrations.AddConstraint(
            model_name='accessrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'selection_set'), name='uniq_request_selection_set'),
        ),
        migrations.AddConstraint(
            model_name='permissionvisibilityruleblock',
            constraint=models.UniqueConstraint(fields=('rule', 'block'), name='uniq_rule_block'),
        ),
        migrations.AddConstraint(
            model_name='permissionvisibilitytrigger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('module__isnull', False), ('level__isnull', True), ('sublevel__isnull', True)), models.Q(('module__isnull', True), ('level__isnull', False), ('sublevel__isnull', True)), models.Q(('module__isnull', True), ('level__isnull', True), ('sublevel__isnull', False)), _connector='OR'), name='trigger_exactly_one_fk'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', 'created_at'], name='catalog_acc_status_881559_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['kind', 'created_at'], name='catalog_acc_kind_dc460b_idx'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetactionvalue',
            constraint=models.UniqueConstraint(fields=('selection_set', 'action_permission'), name='uniq_selection_action_value'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetcashregister',
            constraint=models.UniqueConstraint(fields=('selection_set', 'cash_register'), name='uniq_selection_cash_register'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetcontrolpanel',
            constraint=models.UniqueConstraint(fields=('selection_set', 'control_panel'), name='uniq_selection_control_panel'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetlevel',
            constraint=models.UniqueConstraint(fields=('selection_set', 'level'), name='uniq_selection_level'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetmatrixpermission',
            constraint=models.UniqueConstraint(fields=('selection_set', 'permission'), name='uniq_selection_matrix_permission'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetmodule',
            constraint=models.UniqueConstraint(fields=('selection_set', 'module'), name='uniq_selection_module'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetpaymentmethod',
            constraint=models.UniqueConstraint(fields=('selection_set', 'payment_method'), name='uniq_selection_payment_method'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetsublevel',
            constraint=models.UniqueConstraint(fields=('selection_set', 'sublevel'), name='uniq_selection_sublevel'),
        ),
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_seller_per_company_name'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetseller',
            constraint=models.UniqueConstraint(fields=('selection_set', 'seller'), name='uniq_selection_seller'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_warehouse_per_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='selectionsetwarehouse',
            constraint=models.UniqueConstraint(fields=('selection_set', 'warehouse'), name='uniq_selection_warehouse'),
        ),
    ]
