# Generated by Django 6.0 on 2025-12-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='selection_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.permissionselectionset'),
        ),
        migrations.CreateModel(
            name='AccessRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.accessrequest')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='catalog.permissionselectionset')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud',
                'verbose_name_plural': 'Ítems de solicitud',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('request', 'selection_set'), name='uniq_request_selection_set')],
            },
        ),
    ]
