# Generated by Django 6.0 on 2025-12-21 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_accessrequest_selection_set_accessrequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionselectionset',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_sets', to='catalog.branch'),
        ),
    ]
