# Generated by ChatGPT on 2025-12-21
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_permissionselectionset_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="same_modules_for_all",
            field=models.BooleanField(default=True),
        ),
    ]
