# Generated by Django 6.0 on 2025-12-21 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_accessrequest_same_modules_for_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionSetLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.erpmodulelevel')),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_levels', to='catalog.permissionselectionset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('selection_set', 'level'), name='uniq_selection_level')],
            },
        ),
        migrations.CreateModel(
            name='SelectionSetSubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_sublevels', to='catalog.permissionselectionset')),
                ('sublevel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.erpmodulesublevel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('selection_set', 'sublevel'), name='uniq_selection_sublevel')],
            },
        ),
    ]
