# Generated by Django 6.0 on 2025-12-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_selectionsetlevel_selectionsetsublevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectionsetsublevel',
            options={'verbose_name': 'Subnivel seleccionado', 'verbose_name_plural': 'Subniveles seleccionados'},
        ),
        migrations.AlterField(
            model_name='selectionsetsublevel',
            name='selection_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='catalog.permissionselectionset'),
        ),
    ]
